[workspace]
members = ["e2e", "stacks", "stacksexport", "tracing-stacks"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 16
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = 1
