[package]
name = "tracing-past"
version = "0.1.0"
edition = "2021"

[dependencies]
probe = "0.5.1"
tracing = "0.1.40"
tracing-core = "0.1.32"
tracing-subscriber = "0.3.18"

[build-dependencies]
version_check = "0.9.4"