name: release
run-name: release ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
    release:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:
            - 
                name: download artifacts
                uses: actions/download-artifact@v4
            - 
                name: create Release
                uses: actions/create-release@v1
                id: create_release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name:  ${{ github.ref_name }}
                    release_name: Release ${{ github.ref_name }} 
                    draft: false
                    prerelease: true
            - name: archive binary
              run: tar -czvf stacks-x86_64-unknown-linux-gnu.tar.gz stacks-x86_64-unknown-linux-gnu/stacks
              
            - name: upload stacks binary
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./stacks-x86_64-unknown-linux-gnu.tar.gz
                asset_name: stacks-x86_64-unknown-linux-gnu.tar.gz
                asset_content_type: application/gzip
    