name: test

on:
  pull_request:
    branches:
      - "**"
  workflow_call:

jobs:
  build:
    name: test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        profile: [dev]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: deps
        run: |
          sudo apt install -y build-essential autoconf clang-15 flex bison pkg-config autopoint
          sudo ln -s /usr/include/asm-generic /usr/include/asm
          sudo rm -f /bin/clang
          sudo ln -s /usr/bin/clang-15 /bin/clang
      - name: cargo test
        run: cargo test --profile=${{ matrix.profile }} --locked
      - name: cargo build
        run: CLANG=clang-15 cargo build --bins --examples --profile=${{ matrix.profile }} --locked
      - name: e2e test (runs with sudo)
        run: |
          if [ "${{ matrix.profile }}" = "dev" ]; then
            sudo RUST_LOG="stacks=debug,e2e=debug" ./target/debug/e2e ./target/debug/stacks ./target/debug/examples
          else
            echo "Error: Profile '${{ matrix.profile }}' is not expected."
            exit 1
          fi

  clippy:
    name: lint with clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          sudo apt install -y build-essential autoconf clang-14 flex bison pkg-config autopoint
          sudo ln -s /usr/include/asm-generic /usr/include/asm
          sudo rm -f /bin/clang
          sudo ln -s /usr/bin/clang-14 /bin/clang
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --locked --no-deps --all-targets --tests -- -D warnings 

  rustfmt:
    name: lint formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check
