[package]
name = "tracing-stacks"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = """
Basic integration of usdt probes with tracing crate. 
"""

[dependencies]
probe = "0.5.1"
tracing = "0.1.40"
tracing-core = "0.1.32"
tracing-subscriber = "0.3.18"
